### ISSUE TITLE
allow user to define their buffer size

### ISSUE THREAD

**Issue by stew8908** [mengguang/minihdlc#2]
The send frame to buffer is a cool function call. But it would be nice if you could make it larger or smaller based on your needs

An externed constant in the header file I feel would be most helpful.

`extern uint16_t MINIHDLC_MAX_FRAME_LENGTH;` instead of `#define MINIHDLC_MAX_FRAME_LENGTH 64`

**Comment by mengguang** [comment]
Please send a pull request. thanks.

**Comment by GrauBlitz** [comment]
Just stumbled upon this, you can just capsule the #define:

Custom minihdlc.h:
```c
#ifndef MINIHDLC_MAX_FRAME_LENGTH
#define MINIHDLC_MAX_FRAME_LENGTH (64)
#endif
```

Your custom code:
```c
#define MINIHDLC_MAX_FRAME_LENGTH (128)
#include "minihdlc.h"
```

Or set it with a compiler flag: `gcc -DMINIHDLC_MAX_FRAME_LENGTH=(128)`

Solving this with an extern variable seems like a odd solution to me, the buffer size is imo only interesting at compile time when you decide on the inner protocol and the device you want to use (memory constrains).

@mengguang I think this may be closed, but if you are interested I may provide a PR with the above. Btw thanks for this project!

PS: It should also be possible to use the custom code without changing the header, but a #ifdef seems prettier to me 😃

**Comment by mengguang** [comment]
Very Good.   
I like the capsule define idea. commit on 16b8d861fa5ab0f20db58aed4bcb5d0d5e8bbcb1  
Thanks.
