### ISSUE TITLE
Problem Using this Lib on AVR

### ISSUE THREAD

**Issue by peimangordany** [mengguang/minihdlc#4]
Hello, Thanks for the library, I had a problem using this library on AVR while everything was perfect on X64. I found that the problem was in Line 98 of "minihdlc.c".
Instead of "if(mhst.frame_position - 2 >= 0)" there should be "if (mhst.frame_position>= 2)" because "frame_position" is a uint16 and this will result in a problem on some compilers.

**Comment by mengguang** [comment]
Good, I will check this later. Thanks.

**Comment by mengguang** [comment]
fixed.
